flask_social_auth/chore/forms.py
"""Forms for the user blueprint."""
from flask_wtf import Form
from wtforms import PasswordField, TextField
from wtforms.validators import DataRequired, Email, Length

from .models import User


class RegisterForm(Form):

    """Registration form."""

    email = TextField(
        'Email',
        validators=[DataRequired(), Email(), Length(min=6, max=254)]
    )
    password = PasswordField(
        'Password',
        validators=[DataRequired(), Length(min=6, max=255)]
    )

    def __init__(self, *args, **kwargs):
        """Init the form."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        email = User.query.filter_by(email=self.email.data).first()
        if email:
            self.email.errors.append('Email already registered')
            return False
        return True

flask_social_auth/user/forms.py
"""Forms for the user blueprint."""
from flask_wtf import Form
from wtforms import PasswordField, TextField
from wtforms.validators import DataRequired, Email, Length

from .models import User


class RegisterForm(Form):

    """Registration form."""

    email = TextField(
        'Email',
        validators=[DataRequired(), Email(), Length(min=6, max=254)]
    )
    password = PasswordField(
        'Password',
        validators=[DataRequired(), Length(min=6, max=255)]
    )

    def __init__(self, *args, **kwargs):
        """Init the form."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        email = User.query.filter_by(email=self.email.data).first()
        if email:
            self.email.errors.append('Email already registered')
            return False
        return True

flask_social_auth/app.py
"""The app module, containing the app factory function."""
import flask_login
from flask import Flask, g, redirect, render_template
from flask_social_auth import user, public
from flask_social_auth.extensions import db, login_manager, bcrypt
from flask_social_auth.settings import DevConfig
from social.apps.flask_app.default.models import init_social
from social_flask.routes import social_auth
from social.apps.flask_app.template_filters import backends
from social.exceptions import SocialAuthBaseException


def create_app(config_object=DevConfig):
    """The application factory.

    Explained here: http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    register_extensions(app)
    register_blueprints(app)
    register_before_requests(app)
    register_errorhandlers(app)
    register_context_processors(app)
    register_teardown_appcontext(app)
    
    db.init_app(app)
    return app


def register_extensions(app):
    """Register Flask extensions."""
    bcrypt.init_app(app)
    login_manager.init_app(app)
    db.init_app(app)
    init_social(app, db.session)


def register_blueprints(app):
    """Register own and 3rd party blueprints."""
    app.register_blueprint(social_auth)

    app.register_blueprint(user.views.blueprint)
    app.register_blueprint(public.views.blueprint)


def register_errorhandlers(app):
    """Add errorhandlers to the app."""
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)

    def social_error(error):
        if isinstance(error, SocialAuthBaseException):
            return redirect('/socialerror')
    app.errorhandler(500)(social_error)


def register_before_requests(app):
    """Register before_request functions."""
    def global_user():
        g.user = flask_login.current_user
    app.before_request(global_user)


def register_context_processors(app):
    """Register context_processor functions."""
    def inject_user():
        try:
            return {'user': g.user}
        except AttributeError:
            return {'user': None}
    app.context_processor(inject_user)
    app.context_processor(backends)


def register_teardown_appcontext(app):
    """Register teardown_appcontext functions."""
    def commit_on_success(error=None):
        if error is None:
            db.session.commit()
    app.teardown_appcontext(commit_on_success)

flask_social_auth/chore/__init__.py
from . import views

flask_social_auth/chore/views.py
"""The views for the user blueprint."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint(
    'user',
    __name__,
    url_prefix='/users',
    static_folder='../static'
)


@blueprint.route('/')
@login_required
def members():
    """Placeholder page for members only."""
    return render_template('users/members.html')


@blueprint.route('/foo')
@login_required
def foo_fn():
    """Placeholder page for members only."""
    return render_template('users/members.html')

flask_social_auth/user/__init__.py
from . import views

flask_social_auth/user/views.py
"""The views for the user blueprint."""
from flask import Blueprint, render_template
from flask_login import login_required

import sys
import os
import dateutil
from datetime import datetime, timedelta
import inflection

blueprint = Blueprint(
    'user',
    __name__,
    url_prefix='/users',
    static_folder='../static'
)


@blueprint.route('/')
@login_required
def members():
    """Placeholder page for members only."""
    return render_template('users/members.html')


@blueprint.route('/foo')
@login_required
def foo_fn():
    """Placeholder page for members only."""
    return render_template('users/members.html')

#SO THERE REALLY NEEDS TO BE AN INTERMEDIARY STEP THAT COLLECTS THE ADDRESS AND LOGS THAT IN ADDITION TO THE REST


@blueprint.route('/chores/show_upcoming')
def index():
    """Homepage."""
    #if there's a user_id in our Flask session, use that to open the app to the user. Otherwise, send the user to a signup page
    if session.get('user_id', False):
        #show the user their upcoming chores
        #get the current user (email)
        user = dbwrangler.get_current_user()
        user_id = user.user_id
        #return a dictionary of one user's chores for a month, grouped by day
        chores = helpers.chores_by_date(user_id)
        #mark the current datetime, assign to now
        now = datetime.utcnow()
        #define a delta of 4 weeks
        until = now + timedelta(weeks=4)
        #generate a list of datetimes for each day in the next month
        month_of_days_dt = rrule(freq=DAILY, dtstart=now, until=until)
        #cast list of datetimes into human-friendly string format
        month_of_days = [day.strftime("%A, %B %d, %Y") for day in month_of_days_dt]
        #feed the template a month of days, and all chores for the logged in user. Jinja will display chores by day.
        # sys.stderr.write("USER NOT LOGGED IN (PYTHON, ROUTE:'/')\n")
        return render_template("dashboard.html", user=user, chores=chores, month=month_of_days)
    else:
        # sys.stderr.write("USER LOGGED IN (PYTHON, ROUTE:'/')")
        return render_template("homepage.html")


@blueprint.route('/newchore')
def createchore():
    """Render form to enter new chore for the household"""
    return render_template("newchore.html")


@blueprint.route('/newchore', methods=['POST'])
def newchore():
    """Request form contents to create new chore in db"""
    #get info from form template
    name = request.form.get('chore_name')
    description = request.form.get('chore_description')
    duration_hours = request.form.get('duration_hours') or 0
    duration_minutes = request.form.get('duration_minutes') or 0
    #compse duration in minutes
    duration_minutes = (int(duration_hours) * 60 + int(duration_minutes))
    occurance = request.form.get('occurance')
    comment = request.form.get('comment')
    by_time = request.form.get('by-time')
    days_weekly = request.form.getlist('days_weekly')
    date_monthly = request.form.get('date_monthly')
    #send chore details to DB
    dbwrangler.newchore(name, description, duration_minutes, occurance, by_time, 
                  comment, days_weekly, date_monthly)

    return redirect("/")


@blueprint.route('/takeachore', methods=['GET'])
def claimchore():
    """Display a list of available chores and the days on which they occur, for 
    the user to select and claim"""
    user = dbwrangler.get_current_user()
    userchores = Userchore.query.filter_by(address_id=user.address, 
                                            commitment='INIT').all()
    #Below: chores that this belong to this user's address
    address_chores = [Chore.query.filter_by(chore_id=userchore.chore_id).first()
                                     for userchore in userchores]
    chores = []
    for chore in address_chores:
        #gather userchore entries for this chore
        userchores = Userchore.query.filter_by(chore_id=chore.chore_id).all()
        #isolate the item from ^ that is the clean (first) member of that chore inside userchores(table)
        base_userchore = [userchore for userchore in userchores if userchore.commitment == 'INIT']
        #get the rest of the chore data associated with that chore
        days_left = chore.days_weekly.split("|")
        days_left = helpers.find_days_left(chore, userchores, days_left)
        if len(days_left) != 0:
            chores.append(chore)
    for chore in chores:
        #recast the occurance dates for these as lists
        chore.days_weekly = chore.days_weekly.split("|")
        if chore.date_monthly:
            chore.date_monthly = inflect.engine().ordinal(chore.date_monthly)


    return render_template("takeachore.html", chores=chores, 
                            userchores=userchores, user=user)


@blueprint.route('/takechoreform', methods=['POST'])
def feedjsboxes():
    """Get remaining days available for a chore and feed them to JS at takeachore.html"""

    form_chore_id = request.form.get("form_chore_id")

    #get the data in the association table that goes with the chore in the dropdown (as selected by the user). Ultimately want initial entry.
    userchores = Userchore.query.filter_by(chore_id=form_chore_id).all()

    base_userchore = [userchore for userchore in userchores if userchore.commitment == 'INIT']
    #isolate the item from the previous query results that is the clean (first) instance of that chore inside userchorees [above] and get the rest of the chore data associated with that chore from the chores table [below]
    base_chore = Chore.query.filter_by(chore_id=base_userchore[0].chore_id).first()

    #create a variable that will become the unclaimed instances of that chore, initialized as a list of all instances of that chore
    days_left = base_chore.days_weekly.split("|")

    #subtract off instances claimed already
    days_left = helpers.find_days_left(base_chore, userchores, days_left)

    return jsonify({'days_left': days_left,
                    'chore_id': base_chore.chore_id, 
                    'chore_name': base_chore.name,
                    'date_monthly': base_chore.date_monthly,
                    'occurance': base_chore.occurance})


@blueprint.route('/take_weekly_agreements', methods=['POST'])
def take_weekly_agreements():
    """ Get agreed days from form and add them to userchores table in DB, 
        specific to daily and weekly chores"""

    #collect data from form template
    chore_id = request.form.get("chore_id")
    daysagreed = request.form.get("daysagreed")
    daysagreed = daysagreed.split("|")

    #no more unicode
    days_agreed = [str(i) for i in daysagreed]

    #recast agreements from T/F to days of the week (by name)
    days_agreed = [days_of_the_week[i] for i in range(7) if days_agreed[i] == 'true']

    #format list of daily agreements for addition to database (string)
    days_agreed = "|".join(days_agreed)    

    #save to database
    dbwrangler.add_commitment(days_agreed, chore_id)

    #redirect to form for further agreements
    return redirect("/takeachore")


@blueprint.route('/take_monthly_agreements', methods=['POST'])
def take_monthly_agreements():
    """ Get agreed days from form and add them to userchores table in DB, 
        specific to monthly chores"""

    #collect data from form template
    chore_id = request.form.get("chore_id")
    date_monthly = request.form.get("date_monthly")

    #add agreements to database
    dbwrangler.add_commitment(date_monthly, chore_id)

    #redirect to form for further agreements
    return redirect("/takeachore")


@blueprint.route('/user-contributions.json')
def user_contributions_chart():
    """Return a chart of data about household contributions."""

    #get current user according to Flask session
    user = dbwrangler.get_current_user()

    #get all users from the user table sharing their address (so, their housemates)
    all_housemates = User.query.filter_by(address=user.address).all()

    #calculate total minutes of labor wach month for the user and their housemates
    total_household_labor = dbwrangler.total_houehold_labor(user)

    #build a data dictionary to feed jsonify. First entry in the labels list is unclaied labor... total household labor from which we will subtract housemate contributions
    dd_labels = ["Unclaimed"]

    #dd_data will be the minutes per user. Instantiate as an empty list.
    dd_data = []

    #each user gets a unique color
    dd_bgcolors = helpers.color_picker(len(all_housemates)+1)

    #Chart.js lets you select bgcolor for each wedge as one hovers over the chart
    dd_hoverbg = ["#a6a6a6", "#a6a6a6","#a6a6a6","#a6a6a6"]

    leftover_labor = total_household_labor

    #build lists in each field of our data dictionary, with each member of the household at their own index
    for housemate in all_housemates:
        dd_labels.append(housemate.name)
        individual_labor = dbwrangler.individual_labor(housemate.user_id)
        dd_data.append(individual_labor)
        leftover_labor -= individual_labor

    #zeroth index is the unclaimed labor (this from 21 lines above)
    dd_data = [leftover_labor] + dd_data

    data_dict = {
                "labels": dd_labels, 
                "datasets":[{"data":dd_data, 
                "backgroundColor":dd_bgcolors, 
                "hoverBackgroundColor":dd_hoverbg}]
                }
                
    return jsonify(data_dict)

flask_social_auth/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

flask_social_auth/templates/base.html
<html>
<head>
    {% block head %}
    {% endblock %}
     <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
     <link href="/static/style.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Quando" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <a href="/"><img src="/static/logo.png" class="img-fluid tiny-img" alt="Responsive image"></a>
      </ul>
      <ul>
        <li><a href="/logout">Logout</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" id="navbar_menu" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/newchore">Add a new household chore</a></li>
            <li><a href="/takeachore">Volunteer for a chore</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/user">View/Edit Profile</li>
            <li role="separator" class="divider"></li>
            <li><a href="/logout">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% block body %}
{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
{% block scripts %}
{% endblock %}
</script>
</body>
</html>

flask_social_auth/templates/dashboard.html
{% extends 'base.html' %}
{% block head %}
<script src="https://code.jquery.com/jquery.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.1/Chart.js"></script> -->
{% endblock %}
{% block body %}
<!-- <div class="contribution-chart">
  <canvas id="donutChart"></canvas>
</div> -->
<div class="indent_content">
    {% if chores %}
    <h2>Upcoming Chores</h2>
    Mouse-over for more details
    <div id="user_chore_display">
    <br>
    <br>
    {% endif %}
    {% for day in month %}
        {% if day in chores %}
        <h3 class="chore_header">{{ day }}<br>
        <div class="blue_line"></div></h3>
            <div class="indent_content">
                {% for chore in chores[day] %}
                <a href="#" data-toggle="tooltip" title="" data-original-title="{{ chore.description }}"> 
                    {{ chore.name }} </a> {% if chore.by_time %} before 
                    {{chore.by_time}}{% endif %}
                    <br>
                {% endfor %}
            </div>
            <br>
        {% endif %}
    {% endfor %}
    </div>
</div>
  <!-- <div id="donutLegend" class="chart-legend"></div> LEGEND (DISABLED FOR NOW)-->
<!-- <script src="/static/chartscripts.js"></script> -->
<script>$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock %}

flask_social_auth/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Steven Loria</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:sloria1@gmail.com">Contact</a></li>
    </ul>
  </small>
</footer>

flask_social_auth/templates/homepage.html
{% extends 'loginbar.html' %}
{% block head %}
    <title>Happy Home
    </title>
{% endblock %}
{% block body %}
{% endblock %}

flask_social_auth/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>
    {% block page_title %}

    My Flask App

    {% endblock %}
  </title>

  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">

  {% block css %}{% endblock %}

</head>

<body class="{% block body_class %}{% endblock %}">
  
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->

{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

flask_social_auth/templates/loginbar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id" content="953238239415-4mvdahlpba71b5c5aqphsva7pvt2qlto.apps.googleusercontent.com">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Quando" rel="stylesheet">
    <link href="/static/style.css" rel="stylesheet">
  </head>
  <body>
    <div class="container">
        <div class="col-xs-12 col-md-6">
            <br><br>
            <h1 class="heading"><img src="static/logo.png" class="logo">Happy Home</h1>
            <p id='intro-text' class='block'>Adulting made easier! Distribute the workload of household maintainance. Help you and your roomates get on with your lives, without losing track of whose turn it is to take out the trash!
            </p>
        </div>
        <div class="col-xs-12 col-md-6 login_fields">
            <br><br>
            <form action="/login" method="POST">
                <input class="form_input" type="email" name="email" placeholder="Email" required><br>
                <input class="form_input" type="password" name="password" placeholder="Password" required><br><br>
                <input class="form_input" type="submit" value="Log In">
            </form><br>
            <div class="g-signin2" data-onsuccess="onSignIn" data-theme="dark"></div><br>


            <a href="/signup"><button type="button">Sign Up</button></a><br>
        </div>
    </div>
    <script>
      function onSignIn(googleUser) {
        // Useful data for your client-side scripts:
        var profile = googleUser.getBasicProfile();
        console.log("ID: " + profile.getId()); // Don't send this directly to your server!
        console.log('Full Name: ' + profile.getName());
        console.log('Given Name: ' + profile.getGivenName());
        console.log('Family Name: ' + profile.getFamilyName());
        console.log("Image URL: " + profile.getImageUrl());
        console.log("Email: " + profile.getEmail());

        // The ID token you need to pass to your backend:
        var id_token = googleUser.getAuthResponse().id_token;
        console.log("ID Token: " + id_token);

        var xhr = new XMLHttpRequest();
        xhr.open('POST', 'http://localhost:5000/gtokensignin');
        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        xhr.onload = function(response) {
          console.log('Signed in as: ' + xhr.responseText);
          if (xhr.responseText === "FLASK SEES USER") {
            window.location = "/more_info";
          } else if (xhr.responseText ===  "FLASK SEES NO USER") {
            window.location = "/";
          }
        };
        xhr.send('idtoken=' + id_token);
      };
    </script>
  </body>
</html>

flask_social_auth/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('public.home') }}">

        My Flask App

      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('public.home') }}">Home</a></li>
        <li><a href="{{ url_for('public.about') }}">About</a></li>
      </ul>
      {% if current_user and current_user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text">
              <a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a>
            </p>
        </li>
        <li>
          <a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a>
        </li>

      </ul>
      {% else %}
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="{{ url_for('public.login') }}">Login</a>
        </li>
        <li>
          <a href="{{ url_for('public.register') }}">Sign up</a>
        </li>
      </ul>
      </form>
      {% endif %}
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

flask_social_auth/templates/new_user.html
{% extends 'base.html' %}
{% block body %}
<div class="indent_content">
    <form action="/signup" method="POST">
        Name: <input type="text" id="name_field" class="form_input" name="name" 
        placeholder="Name" required><br>
        Last Name: <input type="text" class="form_input" id="lname_field" 
        name="lname" placeholder="Last Name" required><br>
        Email: <input type="email" class="form_input" id="email_field" 
        name="email" placeholder="Email" required><br>
        Password: <input type="password" class="form_input" id="password_field" 
        name="password" placeholder="Password" required><br>
        <input type="submit" id="sign_up_button" value="Sign Up">
    </form>
</div>
{% endblock %}
{% block script %}
    $(".user_img_option").click($("#user_avatar").attr(""))
{% endblock %}

flask_social_auth/templates/new_user_more.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block body %}
<div>
    <form action="/complete_registration" method="POST">
        <div class="col-xs-11 col-sm-10">
            Street Address: <input type="text" class="form_input" id= "address" 
            name="address" placeholder="Street Address">
            <br>
            Apartment:<input type="text" class="form_input" id= "apartment" 
            name="apartment" placeholder="#">
            <br>
            City: <input type="text" class="form_input" id="city" name="city" 
            placeholder="City" required><br>
            State: <input type="text" class="form_input" id= "state" name="state" 
            placeholder="State" required>
            <br>
            Zip: <input type="text" class="form_input" id="zipcode" name="zipcode" 
            placeholder="ZIP" required>
            <br>
            Phone Number: <input type="text" class="form_input" name="phone_number" 
            placeholder="Phone" required>
        </div>
        <div class="col-xs-1 col-sm-2">
            <input type="submit" id="complete_sign_up" value="Sign Me Up!">
        </div>
        <div class="row" id="user_avatar_row">
            <input type="text" id="user_avatar" name="user_avatar" hidden><br>
        </div>
        <div class="row" id="user_avatars">
            {% for file_number in range(23) %}
            <div class="col-xs-6 col-sm-3 col-md-2">
                <a href="#" class="thumbnail">
                    <img src="/static/user_img/{{ file_number }}.png" 
                    class="img-fluid user_img_option" id="{{ file_number }}.png"
                    alt="Responsive image">
                </a>
            </div>
            {% endfor %}
    </div>
    </form>
</div>
{% endblock %}
{% block scripts %}
console.log("I see the scripts!");
console.log($("#user_avatar").val());

$(".thumbnail").click(function(){
    $("#user_avatar").val($(this).find("img").attr("src"));
});

{% endblock %}

flask_social_auth/templates/user.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="col-xs-12 col-md-2">
        <img src="{{ user.avatar_src }}" class="img-fluid" alt="Responsive image">
    </div>
    <div class="col-xs-12 col-md-4 indent_content">
    <div>
            Name: {{ user.name }} {{ user.lname[0] }}.<br>
            Email: {{ user.email }}<br>
            Phone: ({{ user.phone_number[0:3] }}){{ user.phone_number[3:6] }}-{{ user.phone_number[6:] }}<br>
            Address:<br>
            <div class="indent_content">
            {{ address.address_street_num }} {{ address.address_street }} {% if address.apartment %}, {{ address.apartment }} {% endif %}<br>
            {{ address.address_city }}, {{ address.address_state }} {{ address.address_zip }}<br>
            </div><br>
            <button id="profil_edit_button">Edit Profile</button>
    </div>
    </div>
    <div class="col-xs-12 col-md-6">
        Your Household:<br>
        {% for housemate in all_housemates %}
            <div class="col-xs-1 housemate_img">
            <img src="{{ housemate.avatar_src }}" class="img-fluid tiny-img" alt="Responsive image"><br>
            {{ housemate.name }}
            </div>
        {% endfor %}
    </div>
</div>
<script>
    $()
</script>
{% endblock %}